Repository yyueniao/miters, pull requests merged in 2023-07, with the labels that each got.

#1 build: `eslint`
  .eslintrc
  .github/workflows/ci.yaml
  env.d.ts
  index.ts
  package-lock.json
  package.json
Labels: build

#3 build: `prettier`
  .eslintrc
  .github/workflows/ci.yaml
  env.d.ts
  index.ts
  package-lock.json
  package.json
Labels: build

#5 build(eslint): `one-var` config
  .eslintrc
Labels: build

#6 build(prettier): create configuration
  .prettierrc
Labels: build

#4 feat: first command
  commands/index.ts
  commands/ping.ts
  index.ts
  tsconfig.json
Labels: enhancement

#7 docs(README): introduction and contribute guide
  .env.example
  README.md
Labels: documentation

#9 docs(README): delete license and contact
  README.md
Labels: documentation

#19 refactor(commands/ping): avoid hardcoding response
  commands/ping.ts
  contents/ping.ts
Labels: refactoring
